"""init api_keys and mail_transactions

Revision ID: 524273231462
Revises: 
Create Date: 2026-09-08 11:03:31.982188
"""
from alembic import op
import sqlalchemy as sa

revision = '524273231462'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_token', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('allowed_from_addresses', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_token'), 'api_keys', ['key_token'], unique=True)
    op.create_table('mail_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('to_addresses', sa.JSON(), nullable=False),
    sa.Column('cc_addresses', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_transactions_client_id'), 'mail_transactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_mail_transactions_status'), 'mail_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_mail_transactions_task_id'), 'mail_transactions', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mail_transactions_task_id'), table_name='mail_transactions')
    op.drop_index(op.f('ix_mail_transactions_status'), table_name='mail_transactions')
    op.drop_index(op.f('ix_mail_transactions_client_id'), table_name='mail_transactions')
    op.drop_table('mail_transactions')
    op.drop_index(op.f('ix_api_keys_key_token'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
